name: GitHub Actions python
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 python
on: [push]
jobs:
  check_python_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup Python
        uses: actions/setup-python@v4.6.0
      - name: Check Python version
        run: python --version
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Pylint
        run: pylint app.py
